import { products } from "@/assets/productData";
import Image from "next/image";
import { assets } from "@/assets/assets";
import Carousel from "@/components/Carousel";
import ProductCard from "@/components/ProductCard";
import Brand from "@/components/Brand";
import { Metadata } from "next";
import Badge from "@/components/Badge";
import { getAllCategories } from "@/services/category.service";
import { ICategory } from "@/types/category";
import { Button } from "@/components/Button";
import { IWebResponse } from "@/types/web";

export const metadata: Metadata = {
  title: "NextCart App",
  description: "Generated by create next app",
};

export default async function Home() {
  const { data: categories }: IWebResponse<ICategory[]> =
    await getAllCategories();
  return (
    <main className="mx-20 my-24 mt-[60x]">
      <Carousel />
      {/* categories */}
      <div className="mt-8 flex flex-row items-center justify-between">
        <ul className="flex flex-row flex-wrap gap-4">
          {categories.slice(0, 4).map(({ name }: ICategory, idx) => (
            <Badge key={idx} name={name} />
          ))}
        </ul>
        <Button className="text-lg font-semibold">See all</Button>
      </div>
      {/* products */}
      <div className="mt-8 grid grid-cols-4 gap-8">
        {products.map((product) => (
          <ProductCard product={product} key={product.id} />
        ))}
      </div>

      {/* content 1 */}
      <div className="mt-10 flex flex-row items-center justify-between rounded-xl bg-slate-50 px-6 shadow-sm">
        {/* Left Image */}
        <div className="flex-shrink-0">
          <Image
            priority
            src={assets.jbl_soundbox_image}
            alt="JBL Soundbox"
            height={250}
            width={250}
            className="object-contain"
            style={{
              height: "auto",
              width: "auto",
            }}
          />
        </div>

        {/* Text Content */}
        <div className="mx-6 max-w-2xl text-center">
          <h1 className="text-2xl font-extrabold leading-snug text-green-600">
            Level Up Your Gaming
            <br />
            Experience
          </h1>
          <p className="mt-3 text-base font-medium text-gray-600">
            Experience the ultimate gaming experience with our latest
            controller. Immerse yourself in stunning graphics and lightning-fast
            response times. Get ready to conquer your favorite games like never
            before!
          </p>
          <Button variant="primary" size="lg" className="mt-4">
            Explore More
          </Button>
        </div>

        {/* Right Image */}
        <div className="flex-shrink-0">
          <Image
            priority
            src={assets.md_controller_image}
            alt="Gaming Controller"
            height={250}
            width={250}
            className="object-contain"
            style={{
              height: "auto",
              width: "auto",
            }}
          />
        </div>
      </div>

      {/* content 2 */}

      <div className="mt-10 flex flex-col items-center justify-between">
        <h1 className="text-3xl font-semibold tracking-wider text-slate-700">
          Subscribe now & get 20% off
        </h1>
        <p className="mt-3 text-base font-medium text-gray-500">
          Lorem Ipsum is simply dummy text of the printing and typesetting
          industry.
        </p>
        <div className="flex w-3/4 flex-row items-center justify-between rounded-xl px-6 py-8">
          <input
            type="email"
            placeholder="Enter your email"
            className="w-full rounded-l-xl border border-slate-300 px-4 py-5 text-slate-500 outline-none transition focus:border-green-500 focus:ring-1 focus:ring-green-500"
          />
          <button className="rounded-r-xl bg-green-500 px-8 py-5 font-semibold tracking-wider text-slate-50 transition hover:bg-green-600">
            Subscribe
          </button>
        </div>
      </div>

      {/* brands */}
      <Brand />
    </main>
  );
}
